# Generated by Django 4.2.3 on 2024-12-04 14:42

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cves', '0002_add_cve_upsert_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertIstProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certist_id', models.IntegerField()),
                ('vendor', models.CharField(max_length=256)),
                ('product', models.CharField(max_length=256)),
                ('product_category', models.CharField(max_length=1024)),
                ('version', models.CharField(max_length=256)),
                ('created', models.DateField()),
                ('obsoleted', models.DateField(null=True)),
                ('monitoring_level', models.IntegerField()),
                ('cpes', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'advancedcve_certistproducts',
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('vendor'), name='gin_trgm_ops'), name='ix_istproducts_vendor'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('product'), name='gin_trgm_ops'), name='ix_istproducts_product'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('product_category'), name='gin_trgm_ops'), name='ix_istproducts_product_cat'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('version'), name='gin_trgm_ops'), name='ix_istproducts_version')],
            },
        ),
        migrations.CreateModel(
            name='CertIstAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_number', models.CharField(max_length=256)),
                ('issuer', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('titles', models.JSONField(default=dict)),
                ('descriptions', models.JSONField(default=dict)),
                ('history', models.JSONField(default=list)),
                ('vulnerability_class', models.JSONField(default=dict)),
                ('system_information', models.JSONField(default=dict)),
                ('cvss', models.JSONField(default=dict)),
                ('references', models.JSONField(default=list)),
                ('solutions', models.JSONField(default=list)),
                ('affected_products', models.ManyToManyField(to='advancedcve.certistproduct')),
                ('cves', models.ManyToManyField(to='cves.cve')),
            ],
            options={
                'db_table': 'advancedcve_certistalerts',
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('ref_number'), name='gin_trgm_ops'), name='ix_istalert_ref_number'), django.contrib.postgres.indexes.GinIndex(fields=['titles'], name='ix_istalerts_titles'), django.contrib.postgres.indexes.GinIndex(fields=['descriptions'], name='ix_istalerts_descriptions'), django.contrib.postgres.indexes.GinIndex(fields=['history'], name='ix_istalerts_history'), django.contrib.postgres.indexes.GinIndex(fields=['system_information'], name='ix_istalerts_system_info'), django.contrib.postgres.indexes.GinIndex(fields=['references'], name='ix_istalerts_references'), django.contrib.postgres.indexes.GinIndex(fields=['solutions'], name='ix_istalerts_solutions')],
            },
        ),
        migrations.CreateModel(
            name='CertIstAdvisory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_number', models.CharField(max_length=256)),
                ('issuer', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('titles', models.JSONField(default=dict)),
                ('descriptions', models.JSONField(default=dict)),
                ('history', models.JSONField(default=list)),
                ('vulnerability_class', models.JSONField(default=dict)),
                ('system_information', models.JSONField(default=dict)),
                ('cvss', models.JSONField(default=dict)),
                ('references', models.JSONField(default=list)),
                ('solutions', models.JSONField(default=list)),
                ('affected_products', models.ManyToManyField(to='advancedcve.certistproduct')),
                ('cves', models.ManyToManyField(to='cves.cve')),
            ],
            options={
                'db_table': 'advancedcve_certistadvisories',
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('ref_number'), name='gin_trgm_ops'), name='ix_istadvisories_ref_number'), django.contrib.postgres.indexes.GinIndex(fields=['titles'], name='ix_istadvisories_titles'), django.contrib.postgres.indexes.GinIndex(fields=['descriptions'], name='ix_istadvisories_descriptions'), django.contrib.postgres.indexes.GinIndex(fields=['history'], name='ix_istadvisories_history'), django.contrib.postgres.indexes.GinIndex(fields=['system_information'], name='ix_istadvisories_system_info'), django.contrib.postgres.indexes.GinIndex(fields=['references'], name='ix_istadvisories_references'), django.contrib.postgres.indexes.GinIndex(fields=['solutions'], name='ix_istadvisories_solutions')],
            },
        ),
    ]
